version: '3.9'

services:
  backend:
    build: 
      context: ./backend
    container_name: backend_app
    ports:
      - "3001:3001"
    environment:
      - DB_CONNECTION_STRING=mongodb://mongo:27017/week06_lab
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - backend
  
  frontend:
    build: 
        context: ./frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fullstack_network

  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fullstack_network

  mongo-express:
    image: mongo-express:1
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=  
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
    depends_on:
      - mongo
    networks:
      - fullstack_network

volumes:
  mongo_data:

networks:
  fullstack_network:
    driver: bridge